# default palette; colorChange overwrites this on wallpaper change
[global]
    frame_color = "#E06C75"
    foreground = "#ffffff"

[urgency_low]
    background = "#222222"
    foreground = "#888888"

[urgency_normal]
    background = "#111214"
    foreground = "#ffffff"

[urgency_critical]
    background = "#900000"
    foreground = "#ffffff"
    frame_color = "#ff0000"
