;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;      ____        __      __
;     / __ \____  / __  __/ /_  ____ ______
;    / /_/ / __ \/ / / / / __ \/ __ `/ ___/
;   / ____/ /_/ / / /_/ / /_/ / /_/ / /
;  /_/    \____/_/\__, /_.___/\__,_/_/
;                /____/
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[global/wm]
margin-top    = 0
margin-bottom = 0
include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

[bar/main]
width = 100%
height = 46
offset-y = 15px
radius = 17
fixed-center = true
monitor =
background = ${colors.bg}
foreground = ${colors.fg}

border-size = 0
border-color = ${colors.trans}

padding       = 2
module-margin = 1

font-0 = Iosevka Nerd Font:style=Regular:size=11;2

modules-left    = clock menu bspwm
modules-center  = time
modules-right   = pulseaudio memory filesystem network battery

wm-restack = bspwm

cursor-click  = pointer
override-redirect = false
[settings]
screenchange-reload = true

[module/clock]
type = internal/date
interval = 1
date = %H:%M
format = <label>
label = %date%
label-font = 3
label-foreground = ${colors.primary}
label-padding-left = 2
label-padding-right = 2

